Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,7 +6,7 @@ on:
         description: Kernel branch
         default: 'ASB-296_SUSFS_NXT'
         required: true
-      DEFCONFIG: 
+      DEFCONFIG:
         description: Defconfig
         default: 'rsuntk_defconfig'
         required: false
@@ -22,180 +22,173 @@ on:
       NEW_CLANG:
         description: Compile with newer Clang (clang-20)
         type: boolean
-        
+
 jobs:
   build:
     runs-on: ubuntu-latest
     environment: telegramUpload
     steps:
-    - name: Get date
-      id: rundate
-      run: sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "REPO_DATE=`date`" >> $GITHUB_OUTPUT
-    
-    - uses: actions/checkout@v4
-      with:
-        path: kernel_root
-        repository: "Samo141988/kernel_m32"
-        ref: ${{ github.event.inputs.BRANCH }}
-        show-progress: false
-     #   submodules: 'recursive'
-        fetch-depth: 1
-    
-    - name: Prepare dependencies
-      run: |
-        sudo apt update -y
-        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget aria2 curl lz4 -y
-        sudo aptitude install libssl-dev -y
-        sudo apt install lld
-    - name: Fetch toolchains
-      run: |
-        
-        mkdir toolchains
-        cd toolchains
-        #URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r450784/clang-r433403.tar.gz"
-        #URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-gsi/clang-r450784d.tar.gz"
-        #URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz"
-        URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/0998f421320ae02fddabec8a78b91bf7620159f6/clang-r563880.tar.gz"
-        echo "INFO: Fetching clang .."
-        mkdir clang && cd clang && wget -q -O clang.tar.gz $URL && tar -xf clang.tar.gz && rm *.gz && cd ..
-        curl -LSs https://raw.githubusercontent.com/rsuntk/toolchains/refs/heads/README/clone.sh | bash -s androidcc-4.9
-        mv androidcc-4.9 google
-      working-directory: kernel_root
-    - name: Build kernel
-      id: buildKernel
-      run: |
-         export PATH=$(pwd)/toolchains/clang/bin:$PATH
-         export CROSS_COMPILE="$(pwd)/toolchains/google/bin/aarch64-linux-android-"
-         export CROSS_COMPILE_COMPAT="$(pwd)/toolchains/arm-gnu/bin/arm-linux-gnueabi-"
-         export CROSS_COMPILE_ARM32=$CROSS_COMPILE_COMPAT
-         export CLANG_TRIPLE=aarch64-linux-gnu-
-         export KBUILD_BUILD_USER="samo"
-         export KBUILD_BUILD_HOST="samo1408"
-         export BUILD_START=`date`
-         export SELINUX_STATE="Enforcing"
-         export IS_CI=true
-         export DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"
-         export DEVICE="M325FV"
-         export DEVICE_ID="M32"
-         export TARGET_PRODUCT="m32"
-         export KERNELSU="${{ github.event.inputs.KSU }}"
-         export LTO="full"
-         export LLVM=1
-         export LLVM_IAS=1   
-         # Add fix for ftruncate conflict
-         export CFLAGS="-Wno-error"    
-         # Clean and prepare
-         rm -f build.sh fs/exec.c fs/open.c fs/stat.c fs/read_write.c kernel/reboot.c    
-         # Download files
-         cd fs
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/exec.c
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/open.c
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/read_write.c
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/stat.c
-         cd ..
-         cd kernel
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/kernel/reboot.c
-         cd ..
-         aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/build.sh
-         chmod +x build.sh
-         # Build
+      - name: Get date
+        id: rundate
+        run: sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "REPO_DATE=`date`" >> $GITHUB_OUTPUT
+
+      - uses: actions/checkout@v4
+        with:
+          path: kernel_root
+          repository: "Samo141988/kernel_m32"
+          ref: ${{ github.event.inputs.BRANCH }}
+          show-progress: false
+          fetch-depth: 1
+
+      - name: Prepare dependencies
+        run: |
+          sudo apt update -y
+          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget aria2 curl lz4 -y
+          sudo aptitude install libssl-dev -y
+          sudo apt install lld -y
+
+      - name: Fetch toolchains
+        run: |
+          mkdir -p toolchains
+          cd toolchains
+          # URL options commented out
+          # URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/llvm-r450784/clang-r433403.tar.gz"
+          # URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-gsi/clang-r450784d.tar.gz"
+          # URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz"
+          URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/0998f421320ae02fddabec8a78b91bf7620159f6/clang-r563880.tar.gz"
+          echo "INFO: Fetching clang .."
+          mkdir -p clang && cd clang && wget -q -O clang.tar.gz $URL && tar -xf clang.tar.gz && rm -f *.gz && cd ..
+          curl -LSs https://raw.githubusercontent.com/rsuntk/toolchains/refs/heads/README/clone.sh | bash -s androidcc-4.9
+          mv androidcc-4.9 google
+        working-directory: kernel_root
+
+      - name: Build kernel
+        id: buildKernel
+        run: |
+          export PATH=$(pwd)/toolchains/clang/bin:$PATH
+          export CROSS_COMPILE="$(pwd)/toolchains/google/bin/aarch64-linux-android-"
+          export CROSS_COMPILE_COMPAT="$(pwd)/toolchains/arm-gnu/bin/arm-linux-gnueabi-"
+          export CROSS_COMPILE_ARM32=$CROSS_COMPILE_COMPAT
+          export CLANG_TRIPLE=aarch64-linux-gnu-
+          export KBUILD_BUILD_USER="samo"
+          export KBUILD_BUILD_HOST="samo1408"
+          export BUILD_START=`date`
+          export SELINUX_STATE="Enforcing"
+          export IS_CI=true
+          export DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"
+          export DEVICE="M325FV"
+          export DEVICE_ID="M32"
+          export TARGET_PRODUCT="m32"
+          export KERNELSU="${{ github.event.inputs.KSU }}"
+          export LTO="full"
+          export LLVM=1
+          export LLVM_IAS=1
+          # Add fix for ftruncate conflict
+          export CFLAGS="-Wno-error"
+          # Clean and prepare
+          rm -f build.sh fs/exec.c fs/open.c fs/stat.c fs/read_write.c kernel/reboot.c || true
+          # Download files
+          cd fs
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/exec.c
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/open.c
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/read_write.c
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/fs/stat.c
+          cd ..
+          cd kernel
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/kernel/reboot.c
+          cd ..
+          aria2c https://raw.githubusercontent.com/Samo1408/Builder_kernel/m32-new/build.sh
+          chmod +x build.sh
+          # Build
           bash build.sh kernel --jobs $(nproc --all) $DEFCONFIG
-         if [[ "${{ github.event.inputs.KSU }}" = "true" ]]; then
-         KSU_REV_COUNT=$(cd KernelSU-Next && git rev-list --count HEAD)
-         KSU_VERSION=$(expr 10200 + $KSU_REV_COUNT)
-         else
+          if [[ "${{ github.event.inputs.KSU }}" = "true" ]]; then
+            KSU_REV_COUNT=$(cd KernelSU-Next && git rev-list --count HEAD)
+            KSU_VERSION=$(expr 10200 + $KSU_REV_COUNT)
+          else
             KSU_VERSION="No KernelSU"
-            fi
+          fi
           echo "- KernelSU version: $KSU_VERSION"
 
-         if [ -e $(pwd)/include/linux/susfs.h ]; then
+          if [ -e $(pwd)/include/linux/susfs.h ]; then
             SUSFS_VERSION=$(cat ./include/linux/susfs.h | grep -E '^#define SUSFS_VERSION' | cut -d' ' -f3 | sed 's/"//g')
-         else
+          else
             SUSFS_VERSION="Not available"
-         fi
-        
-        ## CREATE buildDetails.txt
-        printf "Localversion: `./getutsrel`
-        Clang version: `clang -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`
-        Build date: `echo $BUILD_START`
-        Defconfig: `echo $DEFCONFIG`
-        KernelSU: `echo $KSU_VERSION`
-        Susfs: `echo $SUSFS_VERSION`
-        LTO: off
-        SELinux: `echo $SELINUX_STATE`
-         " >> buildDetails.txt
-        
-         echo "TITLE=Galaxy `echo $DEVICE_ID` Kernel" >> $GITHUB_ENV
-        
-         echo ""
-         echo "===================================================="
-         strings out/arch/arm64/boot/Image | grep "Linux version"
-         echo "===================================================="
+          fi
 
-         mv out/.config out/build_config.txt
-         gitsha1=$(git rev-parse --short HEAD)
-         buildDetails="`make kernelversion`-`echo $DEVICE`_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
-      working-directory: kernel_root
-      
-    - name: Upload config
-      uses: actions/upload-artifact@v4
-      with:
-        name: Config-${{ steps.buildKernel.outputs.buildDetails }}
-        path: kernel_root/out/build_config.txt
-        
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: Build-${{ steps.buildKernel.outputs.buildDetails }}
-        path: |
-          kernel_root/out/arch/arm64/boot/*.gz
-          kernel_root/out/arch/arm64/boot/dts/mediatek/*.dtb
+          # CREATE buildDetails.txt
+          printf "Localversion: `./getutsrel`\\nClang version: `clang -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`\\nBuild date: `echo $BUILD_START`\\nDefconfig: `echo $DEFCONFIG`\\nKernelSU: `echo $KSU_VERSION`\\nSusfs: `echo $SUSFS_VERSION`\\nLTO: off\\nSELinux: `echo $SELINUX_STATE`\\n" >> buildDetails.txt
 
-    - name: Upload AnyKernel3
-      uses: actions/upload-artifact@v4
-      with:
-        name: M32-${{ steps.buildKernel.outputs.buildDetails }}
-        path: kernel_root/AnyKernel3/*
-        compression-level: 9
-        
-    - name: Upload to Telegram
-      if: github.event.inputs.UPLOAD_TO_TG == 'true'
-      env:
-        CHAT_ID: ${{ secrets.CHAT_ID }}
-        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
-      run: |
-        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
-          ZIP=$(find `pwd` -name "*.zip")
-          git clone https://github.com/rsuntk/rsuntkBotScript.git --depth=1 i && cp ./i/* . && rm -rf i
-          bash $(pwd)/rsuntkbot.sh $ZIP "`cat buildDetails.txt`"
-        fi
-      working-directory: kernel_root
-        
-    - name: Strip LKMs
-      if: github.event.inputs.UPLOAD_LKM == 'true'
-      run: |
-        # Cleanup zip
-        rm -rf *.zip
+          echo "TITLE=Galaxy `echo $DEVICE_ID` Kernel" >> $GITHUB_ENV
 
-        # Create folder
-        mkdir ../kernel_object_tmp
-        mkdir kernel_object
+          echo ""
+          echo "===================================================="
+          strings out/arch/arm64/boot/Image | grep "Linux version"
+          echo "===================================================="
 
-        # Only move neccessary path!
-        find $(pwd) -type f -name "*.ko" -exec mv {} ../kernel_object_tmp \;
-        LIST=$(find ../kernel_object_tmp -type f -name "*.ko")
+          mv out/.config out/build_config.txt
+          gitsha1=$(git rev-parse --short HEAD)
+          buildDetails="`make kernelversion`-`echo $DEVICE`_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
+        working-directory: kernel_root
 
-        # Start stripping
-        for file in $LIST; do
-          echo -e "- Stripping `basename $file`"
-          $(pwd)/toolchains/clang/bin/llvm-strip "$file" --strip-unneeded
-        done
-        mv ../kernel_object_tmp/*.ko $(pwd)/kernel_object/
-      working-directory: kernel_root
-        
-    - name: Upload LKM
-      if: github.event.inputs.UPLOAD_LKM == 'true'
-      uses: actions/upload-artifact@v4
-      with:
-        name: LKM-${{ steps.buildKernel.outputs.buildDetails }}
-        path: kernel_root/kernel_object/*
+      - name: Upload config
+        uses: actions/upload-artifact@v4
+        with:
+          name: Config-${{ steps.buildKernel.outputs.buildDetails }}
+          path: kernel_root/out/build_config.txt
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: Build-${{ steps.buildKernel.outputs.buildDetails }}
+          path: |
+            kernel_root/out/arch/arm64/boot/*.gz
+            kernel_root/out/arch/arm64/boot/dts/mediatek/*.dtb
+
+      - name: Upload AnyKernel3
+        uses: actions/upload-artifact@v4
+        with:
+          name: M32-${{ steps.buildKernel.outputs.buildDetails }}
+          path: kernel_root/AnyKernel3/*
+          compression-level: 9
+
+      - name: Upload to Telegram
+        if: github.event.inputs.UPLOAD_TO_TG == 'true'
+        env:
+          CHAT_ID: ${{ secrets.CHAT_ID }}
+          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
+            ZIP=$(find `pwd` -name "*.zip")
+            git clone https://github.com/rsuntk/rsuntkBotScript.git --depth=1 i && cp ./i/* . && rm -rf i
+            bash $(pwd)/rsuntkbot.sh $ZIP "`cat buildDetails.txt`"
+          fi
+        working-directory: kernel_root
+
+      - name: Strip LKMs
+        if: github.event.inputs.UPLOAD_LKM == 'true'
+        run: |
+          # Cleanup zip
+          rm -rf *.zip || true
+
+          # Create folder
+          mkdir -p ../kernel_object_tmp
+          mkdir -p kernel_object
+
+          # Only move necessary path
+          find $(pwd) -type f -name "*.ko" -exec mv {} ../kernel_object_tmp \;
+          LIST=$(find ../kernel_object_tmp -type f -name "*.ko")
+
+          # Start stripping
+          for file in $LIST; do
+            echo -e "- Stripping `basename $file`"
+            $(pwd)/toolchains/clang/bin/llvm-strip "$file" --strip-unneeded
+          done
+          mv ../kernel_object_tmp/*.ko $(pwd)/kernel_object/ || true
+        working-directory: kernel_root
+
+      - name: Upload LKM
+        if: github.event.inputs.UPLOAD_LKM == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: LKM-${{ steps.buildKernel.outputs.buildDetails }}
+          path: kernel_root/kernel_object/*
